# Generated by Django 4.2 on 2025-04-10 20:12

from django.db import migrations, models
import helper.images


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=helper.images.upload_to
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="tarif_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
