# Generated by Django 4.2 on 2025-04-04 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdersItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=1, verbose_name="Количество")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New order"),
                            ("ready", "Ready for delivery"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        default="Name", max_length=255, verbose_name="Имя покупателя"
                    ),
                ),
                (
                    "custumer_phone",
                    models.CharField(
                        default="+79999999999",
                        max_length=255,
                        verbose_name="Телефон покупателя",
                    ),
                ),
                (
                    "customer_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий покупателя"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                        verbose_name="Компания",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.menuitem",
                        verbose_name="Пункт меню",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
        ),
    ]
