# Generated by Django 4.2 on 2025-04-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_ordersitems_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersitems",
            name="price",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
