# Generated by Django 4.2 on 2025-04-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_ordersitems_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordersitems",
            name="uuid",
        ),
        migrations.AddField(
            model_name="orders",
            name="uuid",
            field=models.UUIDField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
