# Generated by Django 4.2 on 2025-04-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_rename_items_orders_menu_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="owner_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий продавца"
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New order"),
                    ("ready", "Ready for delivery"),
                    ("cancel", "Cancelled"),
                    ("reject", "Rejected"),
                ],
                default="new",
            ),
        ),
    ]
