# Generated by Django 4.2 on 2025-04-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tarifs_logo/"),
                ),
                ("max_workers", models.IntegerField()),
                ("max_menu", models.IntegerField()),
                ("max_items", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
