# Generated by Django 4.2 on 2025-04-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_menuitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
