# Generated by Django 4.2 on 2025-04-13 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_menu_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                blank=True, default="Другое", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="discount",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="discount_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="discount_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
